[app]
name = "sapling_scaffold"
key = "sapling_scaffold"

[app.http]
host = "0.0.0.0"
port = "8010"

[app.grpc]
host = "127.0.0.1"
port = "18010"

[mysql]
host = "127.0.0.1"
port = "3306"
username = "root"
password = "123456"
database = "sapling_scaffold"
config = ""                                              #杂项配置
max_idle_conn = 2                                         #连接池的空闲数大小
max_open_conn = 0                                         #最大打开连接数 0为无限制
schema_dir = "docs/schema/sapling_scaffold.sql"

# xorm 配置
level = "debug"      #日志等级 debug || info || warn || error
out_type = "console" #输出位置 console || file (console:输出到控制台 file:输出到日志文件)
show_sql = false      #在日志记录器上显示SQL语句(debug级别大于info时生效)
director = "log/db" #日志输出目录
maxSize = 1         #切割大小(单位:mb)
max_backups = 10     #保留旧日志文件的最大数目(个)
max_age = 7          #保留旧日志文件的最大天数
compress = false    #是否压缩

[log]
level = "debug"
path = "logs"
format = "text"
console_format = "color"  # color | console | json
to = "stdout"

# zap log
zap_level = "info"             #日志等级 debug || info || warn || error || dpanic || panic || fatal
showLine = true            #是否显示行
outType = "all"            #输出位置 console || file || all (console:输出到控制台 file:输出到日志文件 all:我全都要.jpg)
file_format = "json"       #输出到文件时的输出格式 json || console
director = "log/runtime"   #日志输出目录
maxSize = 1                #切割大小(单位:mb)
maxBackups = 10            #保留旧日志文件的最大数目(个)
maxAge = 7                 #保留旧日志文件的最大天数
compress = false           #是否压缩
